[package]
name = "rquantiles"
version = "0.1.0"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]

[lib]
name = "rquantiles"
path = "src/lib.rs"

[dependencies]
rustr = { version = "0.1.9", features=["engine"] }
